### PR TITLE
Modified function n(e)

### PR DESCRIPTION
**Pull request by ghost**
/scripts/main-built.2016-01-08.js
Jsdoc Comment

### CODE REVIEW

**Comment by dVaffection** [comment]
Hi could you explain what you want to achieve?

**Comment by h3c0r** [comment]
Hi, I was splitting a flac file from a cue and I had an error. I changed MP3 to WAVE and it worked so maybe that was the problem. http://digitalx.org/cue-sheet/examples/ I admire your project by the way, it's very useful

**Comment by dVaffection** [comment]
What extension does music file have?

**Comment by dVaffection** [comment]
Also could you explain to me what exactly you changed? I don't think I'm following you.

**Pull request closed without merging**
