### PR TITLE
add UTF-8 BOM to generated *.cue

### PR DESCRIPTION
**Pull request by ghost**
helps certain software (e.g. foobar2000) to correctly recognize utf-8

### CODE REVIEW

**Review by DmitryVarennikov — APPROVED** [review]

**Comment by dVaffection** [comment]
@frifox please deploy `master`

**Comment by frifox** [comment]
deployed

**Comment by dVaffection** [comment]
@nestorzaburannyi could you verify pls

**Comment by nestorzaburannyi** [comment]
@dVaffection 
Wørks as expected, thanks.

**Pull request merged**
