### PR TITLE
Fixed parsing times in [000:00] format

### PR DESCRIPTION
**Pull request by lindmik**
Parsing only worked for [0:00:00], [00:00:00] and [00:00] times, not for
[000:00] times, which e.g. 1001tracklists.com export their times with.

### CODE REVIEW

**Comment by lindmik** [comment]
Hmm... I should probably figure out how to run the test suite and add a test and so forth. And build a new version, whatever that means. :stuck_out_tongue:

**Comment by lindmik** [comment]
Managed to install requirejs and build new version. Also managed to run tests by changing the paths to relative (I guess I should have run it on a node?).

I'm very much a noob when it comes to npm and Javascript development.

**Comment by lindmik** [comment]
Oh, and I hot deployed the fixes to production. Sorry. :smiling_imp:

**Comment by dVaffection** [comment]
Already deployed? Ok, make sure you didn't break anything

**Comment by lindmik** [comment]
I was too lazy to start installing PHP and stuff at home, so I tested in production. The same way I developed CueNation.

How is cuegenerator normally synced with the GitHub repo? Do you do a Git pull manually from console?

**Comment by dVaffection** [comment]
Yes

**Pull request merged**
