### PR TITLE
Unstaged changes

### PR DESCRIPTION
**Pull request by dVaffection**
Unstaged changes + already merged #9 PR. 

@lindmik do we need `.gitignore` changes and `4|5XX.shtml` files content?

### CODE REVIEW

**Comment by frifox** [comment]
gitignore changes were by me, doubt we wanted to track error logs and backups in the repo

**Comment by lindmik** [comment]
How is unstaged branch used? My changes are in master, so picking my commits from master would be best to keep the branches in sync.

**Comment by frifox** [comment]
Just stuff from server that weren't commited/stage. I added them and pushed to the "unstaged" branch. If don't need anything from that then can just trash that branch

**Comment by dVaffection** [comment]
Ok I merged `master` and resolved all conflicts -- now it's good to go. Please approve if you're ok

**Pull request merged**
